env:
  global:
    CC_TEST_REPORTER_ID=634c89ddb16bad65543236ca41d51dc282320eb5e4b88443b4cffece62a8c75b

language: ruby
rvm:
 - 2.5.0
cache:
  - bundler
  - yarn

before_install: gem install bundler
notifications:
  -false

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - bundle exec rails db:create 
  - bundle exec rails db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# Run the test suites
script:
  - bundle exec rspec spec        # rspec testing

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  api_key:
    secure: "iewJbVCj78FpQjmLIlm092hEYjIvnu8xSA3mBf1qPR73H+hjtQAqDm5Pg37CTT+4q4DkjRMNUfivS/fNUYDZUqWRbJVxLBHRcYKhNxa/UesN0jl4gQdtvZzh0g/a/Xey8MFGHIYMIoGFYwCDEk4iirN8QAFvR1OcVMdxbQDJEyT9bgRmDx94SUWVLxIrIMCU5Un1Xp7jIjI+A5b5T4FQeki8z/FVEgnxlVyEx5oxn95oGKrTwMMs72Ecjs7v68OTO3DUbRDeSCgGJv+idTDMPLywIFjbc27hDuOU0Ki5tF5s4cZtkKi7UNp/z05QI8J8ezg1vKWy55Tn/SOo/fKtHb+dFHEYEwGbwVUSGEYkBaFK/ScDjFMMq7JISF+vccWXjmsa5o/3Cu96p3lMA4QJDkSF1Beo7mrAdBp2ymhPQ9NiJd26HeqfGfcwvuMJC/5wH9Igiwc+OJJAA428U9W+Zpmvnwn0e+iGedKkaX/Zwt/Y0Q+hHWtWsdlyZPzsBqGXDo288UuYo71wS+DSWlMZ4+/zaJNGsau1Hi9cUofuXseXrZ0epPPR0Z10h3LYgI8VN+a5hOxn1lATFmXatllhPQ7qp5COdHISN6GFzUkDFBjd1whY81HL/FWJIceJrsjdautKbZCtSJH8Q1VFDDqNL0Otln2DXjaMb+cNbQ3lSpw="
    run: "rails db:migrate"


